[book]
language = "ja"
multilingual = false
src = "mdbook"
title = "NePP CTF"

[output.html]
additional-css = ["questions/web_devtools/q1/web-devtools-q1.css"]
additional-js = ["questions/web_devtools/q2/web-devtools-q2.js"]