apiVersion: apps/v1
kind: Deployment
metadata:
  name: nepp-ctf-server-deployment
spec:
  selector:
    matchLabels:
      app: nepp-ctf-server
  replicas: 1
  template:
    metadata:
      labels:
        app: nepp-ctf-server
    spec:
      containers:
      - name: server
        image: asia-northeast1-docker.pkg.dev/nepp-cloud/nepp-ctf-server-repository/nepp-ctf-server:latest
        # Predictable Demand pattern
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            memory: "200Mi"